global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Sensor Data Ingestion API
  - job_name: 'sensor-ingestion-api'
    metrics_path: '/metrics'
    static_configs:
      # - targets: ['host.docker.internal:5000']
    # Se estiver rodando no Linux, use:
      - targets: ['172.17.0.1:5000']

  # OpenTelemetry Collector (se estiver usando)
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
      - targets: ['otel-collector:8889']