apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: sensor-ingestion
data:
  rabbitmq.conf: |
    vm_memory_high_watermark.relative = 0.3
    disk_free_limit.absolute = 50MB
    log.console = true