apiVersion: v1
kind: Secret
metadata:
  name: sensor-api-secret
  namespace: sensor-ingestion
type: Opaque
stringData:
  # API Key (base64 ser√° feito automaticamente pelo k8s)
  ApiKey__ApiKey: "dev-api-key-12345"
  
  # RabbitMQ Password
  RabbitMQ__Password: "admin123"