apiVersion: v1
kind: ConfigMap
metadata:
  name: sensor-api-config
  namespace: sensor-ingestion
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  
  # RabbitMQ
  RabbitMQ__Host: "rabbitmq-service"
  RabbitMQ__Port: "5672"
  RabbitMQ__Username: "admin"
  RabbitMQ__VirtualHost: "/"
  RabbitMQ__QueueName: "sensor-data-queue"
  
  # OpenTelemetry
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-service:4317"