apiVersion: v1
kind: Service
metadata:
  name: sensor-api-service
  namespace: sensor-ingestion
  labels:
    app: sensor-api
spec:
  type: NodePort
  selector:
    app: sensor-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP