kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sensor-data-cluster

nodes:
  - role: control-plane
    extraPortMappings:
      # API
      - containerPort: 30080
        hostPort: 5000
        protocol: TCP
      # Grafana
      - containerPort: 30300
        hostPort: 3000
        protocol: TCP
      # Prometheus
      - containerPort: 30900
        hostPort: 9090
        protocol: TCP
      # RabbitMQ
      - containerPort: 30672
        hostPort: 5672
        protocol: TCP
      # RabbitMQ Management
      - containerPort: 31567
        hostPort: 15672
        protocol: TCP